//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrazsToursTipsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourTip
    {
        public int TourTipId { get; set; }
        public string TourName { get; set; }
        public string TourTip1 { get; set; }
    }
}
